[[redirects]]
  from = "http://bouldergarage.it/*"
  to = "https://www.bouldergarage.it/:splat"
  status = 301
  force = true
  priority = 10

[[redirects]]
  from = "https://bouldergarage.it/*"
  to = "https://www.bouldergarage.it/:splat"
  status = 301
  force = true
  priority = 10

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  priority = 5

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  priority = 5

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  priority = 1